# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 23) do

  create_table "assets", :force => true do |t|
    t.column "borrower_id",                        :boolean
    t.column "co_borrower_id",                     :boolean
    t.column "asset_type",                         :string
    t.column "other_asset_type_description",       :string
    t.column "holder_name",                        :string
    t.column "holder_street_address",              :string
    t.column "holder_city",                        :string
    t.column "holder_state",                       :string
    t.column "holder_postal_code",                 :integer
    t.column "account_identifier",                 :integer
    t.column "automobile_make_description",        :string
    t.column "automobile_model_year",              :integer
    t.column "stock_bond_mutual_fund_share_count", :integer
    t.column "life_insurance_face_value_amount",   :decimal, :precision => 8, :scale => 2
    t.column "cash_or_market_value_amount",        :decimal, :precision => 8, :scale => 2
  end

  create_table "borrower_residences", :force => true do |t|
    t.column "borrower_id",                        :integer
    t.column "street_address",                     :string
    t.column "city",                               :string
    t.column "state",                              :string
    t.column "postal_code",                        :string
    t.column "country",                            :string
    t.column "borrower_residency_basis",           :string
    t.column "borrower_residency_duration_months", :integer
    t.column "borrower_residency_duration_years",  :integer
    t.column "borrower_residency_type",            :string
  end

  create_table "borrowers", :force => true do |t|
    t.column "borrower_first_name",              :string
    t.column "borrower_middle_name",             :string
    t.column "borrower_last_name",               :string
    t.column "borrower_name_suffix",             :string
    t.column "borrower_application_signed_date", :date
    t.column "borrower_home_telephone_number",   :string
    t.column "borrower_print_position",          :integer
    t.column "borrower_ssn",                     :string
    t.column "borrower_birth_date",              :date
    t.column "borrower_unparsed_name",           :string
    t.column "borrower_dependent_count",         :integer
    t.column "joint_asset_liability_reporting",  :string
    t.column "marital_status",                   :string
    t.column "schooling_years",                  :integer
    t.column "dependent_ages",                   :string
    t.column "mail_to_street_address",           :string
    t.column "mail_to_street_address2",          :string
    t.column "mail_to_city",                     :string
    t.column "mail_to_state",                    :string
    t.column "mail_to_postal_code",              :string
    t.column "mail_to_country",                  :string
    t.column "loan_application_id",              :integer
  end

  create_table "declarations", :force => true do |t|
    t.column "alimony_child_support_obligation_indicator",                      :boolean
    t.column "bankruptcy_indicator",                                            :boolean
    t.column "borrowed_down_payment_indicator",                                 :boolean
    t.column "citizenship_residency_type",                                      :string
    t.column "co_maker_endorser_of_note_indicator",                             :boolean
    t.column "homeowner_past_three_years_type",                                 :string
    t.column "intent_to_occupy_type",                                           :string
    t.column "loan_foreclosure_or_judgement_indicator",                         :boolean
    t.column "outstanding_judgements_indicator",                                :boolean
    t.column "party_to_lawsuit_indicator",                                      :boolean
    t.column "presently_delinquent_indicator",                                  :boolean
    t.column "prior_property_title_type",                                       :string
    t.column "prior_property_usage_type",                                       :string
    t.column "property_foreclosed_past_seven_years_indicator",                  :boolean
    t.column "borrower_first_time_homebuyer_indicator",                         :boolean
    t.column "dec_desc_alimony_child_support",                                  :string
    t.column "dec_desc_borrowed_down_payment",                                  :string
    t.column "dec_desc_co_maker_endorser_on_note",                              :string
    t.column "dec_desc_declared_bankruptcy_past_seven_years",                   :string
    t.column "dec_desc_delinquency_or_default",                                 :string
    t.column "dec_desc_direct_indirect_foreclosed_property_past_seven_years",   :string
    t.column "dec_desc_obligated_on_loan_foreclosed_or_deed_in_lieu_of_jdgmnt", :string
    t.column "dec_desc_outstanding_judgments",                                  :string
    t.column "dec_desc_party_to_lawsuit",                                       :string
  end

  create_table "dependents", :force => true do |t|
    t.column "borrower_id",         :integer, :null => false
    t.column "dependent_age_years", :integer
  end

  create_table "employers", :force => true do |t|
    t.column "name",                             :string
    t.column "street_address",                   :string
    t.column "city",                             :string
    t.column "state",                            :string
    t.column "postal_code",                      :string
    t.column "telephone_number",                 :string
    t.column "time_in_line_of_work_years",       :integer
    t.column "self_employed_indicator",          :boolean
    t.column "position_description",             :string
    t.column "income_employment_monthly_amount", :decimal, :precision => 8, :scale => 2
    t.column "end_date",                         :date
    t.column "start_date",                       :date
  end

  create_table "government_monitorings", :force => true do |t|
    t.column "gender_type",                                         :string
    t.column "other_race_national_origin_description",              :string
    t.column "race_national_origin_refusal_indicator",              :boolean
    t.column "race_national_origin_type",                           :string
    t.column "hmda_ethnicity_type",                                 :string
    t.column "hmda_race_american_indian_or_alaska_native",          :boolean
    t.column "hmda_race_asian",                                     :boolean
    t.column "hmda_race_black_or_african_american",                 :boolean
    t.column "hmda_race_native_hawaiian_or_other_pacific_islander", :boolean
    t.column "hmda_race_white",                                     :boolean
    t.column "hmda_race_information_not_provided_by_applicant",     :boolean
    t.column "hmda_race_not_applicable",                            :boolean
  end

  create_table "housing_expenses", :force => true do |t|
    t.column "present_first_mortgage_principal_and_interest_amount",             :decimal, :precision => 8, :scale => 2
    t.column "proposed_first_mortgage_principal_and_interest_amount",            :decimal, :precision => 8, :scale => 2
    t.column "present_hazard_insurance_amount",                                  :decimal, :precision => 8, :scale => 2
    t.column "present_homeowners_association_dues_and_condominium_fees_amount",  :decimal, :precision => 8, :scale => 2
    t.column "proposed_homeowners_association_dues_and_condominium_fees_amount", :decimal, :precision => 8, :scale => 2
    t.column "proposed_hazard_insurance_amount",                                 :decimal, :precision => 8, :scale => 2
    t.column "present_mi_amount",                                                :decimal, :precision => 8, :scale => 2
    t.column "proposed_mi_amount",                                               :decimal, :precision => 8, :scale => 2
    t.column "present_other_housing_expense_amount",                             :decimal, :precision => 8, :scale => 2
    t.column "proposed_other_housing_expense_amount",                            :decimal, :precision => 8, :scale => 2
    t.column "present_other_mortgage_loan_principal_and_interest_amount",        :decimal, :precision => 8, :scale => 2
    t.column "proposed_other_mortgage_loan_principal_and_interest_amount",       :decimal, :precision => 8, :scale => 2
    t.column "present_real_estate_tax_amount",                                   :decimal, :precision => 8, :scale => 2
    t.column "proposed_real_estate_tax_amount",                                  :decimal, :precision => 8, :scale => 2
    t.column "present_rent_amount",                                              :decimal, :precision => 8, :scale => 2
    t.column "proposed_ground_rent_amount",                                      :decimal, :precision => 8, :scale => 2
    t.column "present_total_amount",                                             :decimal, :precision => 8, :scale => 2, :default => 0.0
    t.column "proposed_total_amount",                                            :decimal, :precision => 8, :scale => 2, :default => 0.0
  end

  create_table "incomes", :force => true do |t|
    t.column "income_type",          :string
    t.column "monthly_total_amount", :decimal, :precision => 8, :scale => 2
  end

  create_table "liabilities", :force => true do |t|
    t.column "holder_street_address",                  :string
    t.column "holder_city",                            :string
    t.column "holder_state",                           :string
    t.column "holder_postal_code",                     :string
    t.column "alimony_owed_to_name",                   :string
    t.column "account_identifier",                     :string
    t.column "exclusion_indicator",                    :boolean
    t.column "holder_name",                            :string
    t.column "monthly_payment_amount",                 :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "payoff_status_indicator",                :boolean
    t.column "payoff_with_current_assets_indicator",   :boolean
    t.column "remaining_term_months",                  :integer
    t.column "liability_type",                         :string
    t.column "unpaid_balance_amount",                  :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "subject_loan_resubordination_indicator", :boolean
  end

  create_table "loan_applications", :force => true do |t|
    t.column "name",                      :string
    t.column "borrower_name",             :string
    t.column "coborrower_indicator",      :boolean
    t.column "coborrower_name",           :string
    t.column "property_street",           :string
    t.column "property_city",             :string
    t.column "property_state",            :string
    t.column "property_postal_code",      :integer
    t.column "created",                   :date
    t.column "last_updated",              :date
    t.column "status",                    :string
    t.column "no_spouse_indicator",       :boolean
    t.column "other_assets_indicator",    :boolean
    t.column "acknowledgement_indicator", :boolean
  end

  create_table "mortgage_terms", :force => true do |t|
    t.column "mortgage_type",                       :string
    t.column "other_mortgage_type_description",     :string
    t.column "agency_case_identifier",              :integer
    t.column "lender_case_identifier",              :integer
    t.column "borrower_requested_loan_amount",      :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "base_loan_amount",                    :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "requested_interest_rate_percent",     :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "loan_amortization_term_months",       :integer
    t.column "loan_amortization_type",              :string
    t.column "other_amortization_type_description", :string
  end

  create_table "property_purposes", :force => true do |t|
    t.column "street_address",                        :string
    t.column "street_address2",                       :string
    t.column "city",                                  :string
    t.column "state",                                 :string
    t.column "postal_code",                           :integer
    t.column "financed_number_of_units",              :integer
    t.column "property_legal_description",            :string
    t.column "structure_built_year",                  :integer
    t.column "loan_purpose",                          :string
    t.column "property_usage_type",                   :string
    t.column "property_acquired_year",                :integer
    t.column "property_original_cost_amount",         :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "property_existing_lien_amount",         :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "gse_refinance_purpose",                 :string
    t.column "refinance_improvements_type",           :string
    t.column "construction_improvement_costs_amount", :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "gse_title_held_in_names",               :string
    t.column "property_rights_type",                  :string
    t.column "gse_title_manner_held_desc",            :string
    t.column "down_payment_source_desc",              :string
  end

  create_table "reo_properties", :force => true do |t|
    t.column "street_address",              :string
    t.column "street_address2",             :string
    t.column "city",                        :string
    t.column "state",                       :string
    t.column "postal_code",                 :string
    t.column "current_residence_indicator", :boolean
    t.column "disposition_status",          :string
    t.column "gse_property_type",           :string
    t.column "lien_installment_amount",     :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "lien_upb_amount",             :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "maintenance_expense_amount",  :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "market_value_amount",         :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "rental_income_gross_amount",  :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "rental_income_net_amount",    :integer, :limit => 10, :precision => 10, :scale => 0
    t.column "subject_indicator",           :boolean
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "transaction_details", :force => true do |t|
    t.column "alterations_improvements_and_repairs_amount",     :decimal, :precision => 8, :scale => 2
    t.column "borrower_paid_discount_points_total_amount",      :decimal, :precision => 8, :scale => 2
    t.column "estimated_closing_costs_amount",                  :decimal, :precision => 8, :scale => 2
    t.column "mi_and_funding_fee_financed_amount",              :decimal, :precision => 8, :scale => 2
    t.column "mi_and_fundingfee_total_amount",                  :decimal, :precision => 8, :scale => 2
    t.column "prepaid_items_estimated_amount",                  :decimal, :precision => 8, :scale => 2
    t.column "purchase_price_amount",                           :decimal, :precision => 8, :scale => 2
    t.column "refinance_including_debts_to_be_paid_off_amount", :decimal, :precision => 8, :scale => 2
    t.column "sales_concession_amount",                         :decimal, :precision => 8, :scale => 2
    t.column "seller_paid_closing_costs_amount",                :decimal, :precision => 8, :scale => 2
    t.column "subordinate_lien_amount",                         :decimal, :precision => 8, :scale => 2
    t.column "subordinate_lien_heloc_amount",                   :decimal, :precision => 8, :scale => 2
    t.column "fre_reserve_amount",                              :decimal, :precision => 8, :scale => 2
    t.column "fre_reserves_amount",                             :decimal, :precision => 8, :scale => 2
    t.column "cost_of_land_acquired",                           :decimal, :precision => 8, :scale => 2
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
