class HousingExpense < ActiveRecord::Base

  validates_numericality_of :present_first_mortgage_principal_and_interest_amount, :proposed_first_mortgage_principal_and_interest_amount, :present_hazard_insurance_amount, :present_homeowners_association_dues_and_condominium_fees_amount, :proposed_homeowners_association_dues_and_condominium_fees_amount, :proposed_hazard_insurance_amount, :present_mi_amount, :proposed_mi_amount, :present_other_housing_expense_amount, :proposed_other_housing_expense_amount, :present_other_mortgage_loan_principal_and_interest_amount, :proposed_other_mortgage_loan_principal_and_interest_amount, :present_real_estate_tax_amount, :proposed_real_estate_tax_amount, :present_rent_amount

end
